version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    build:
        commands:
            - echo Build started on `date`
            - echo Building the php-fpm Docker image...
            - docker build -f docker/php-fpm/Dockerfile -t $IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION  --target prod .
            - docker tag $IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION
            - docker tag $IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_PHP_FPM:latest
            - echo Building the cron Docker image...
            - docker build --build-arg source_image=$IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION -f docker/nginx/Dockerfile -t $IMAGE_REPO_NAME_NGINX:$CODEBUILD_RESOLVED_SOURCE_VERSION  --target prod .
            - docker tag $IMAGE_REPO_NAME_NGINX:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_NGINX:$CODEBUILD_RESOLVED_SOURCE_VERSION
            - docker tag $IMAGE_REPO_NAME_NGINX:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_NGINX:latest
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker images...
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_PHP_FPM:latest
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_NGINX:$CODEBUILD_RESOLVED_SOURCE_VERSION
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_NGINX:latest
            - printf '[{"name":"app","imageUri":"%s"},{"name":"proxy","imageUri":"%s"}]' "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_NGINX:$CODEBUILD_RESOLVED_SOURCE_VERSION"> imagedefinitions.json

artifacts:
    files:
        - imagedefinitions.json
