version: "3.7"
services:

  postgresql:
    image: postgres:10.6
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=app_db
    ports:
      - "5655:5432"

  webserver:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
      target: base
    environment:
      - VIRTUAL_HOST=stirling-blue.local
      - FPM_CONTAINER_NAME=php-fpm
    volumes:
      - ./app/public:/var/www/symfony/public
    ports:
      - "8988:80"

  php-fpm:
    user: www-data
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      target: dev
    working_dir: /var/www/symfony
    volumes:
      - ./app:/var/www/symfony
      - home:/home/www-data
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-php-ini-overrides.ini
    environment:
      - XDEBUG_CONFIG=remote_enable=1 remote_host=host.docker.internal remote_port=9000 idekey=PHPSTORM
      - PHP_IDE_CONFIG=serverName=api_nps
volumes:
  psql:
  home:
